version: "3.9"

services:
  # ================================= Bot =====================================
  # Generic Rasa bot, used to run console for example.
  bot:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: unless-stopped
    volumes:
      - ./bot/:/bot/
    ports:
      - 5005:5005
      - 5006:5006
      - 5007:5007
      - 5008:5008
      - 5009:5009
    depends_on:
      - actions

  # ================================= Actions =================================
  # Rasa middleware used to connect with external APIs.
  actions:
    image: arthurtemporim/boilerplate:latest
    restart: unless-stopped
    ports:
      - 5055:5055
    volumes:
      - ./bot:/bot
    command: sh -c "make actions"

  # ============================ Webchat Page  =================================
  # A container to run webchat html page
  webchat:
    image: nginx
    ports:
      - 5010:80
    volumes:
      - ./modules/webchat:/usr/share/nginx/html

  # ============================ Telegram Bot =================================
  # Specific Rasa bot integrated with Telegram.
  bot-telegram:
      build:
        context: .
        dockerfile: ./docker/bot.Dockerfile
      volumes:
        - ./bot/:/bot/
      env_file:
        - env/bot-telegram.env
      ports:
        - 5005:5005
      command: sh -c "make telegram"
